spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/freevoice
    username: merovingian
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 900MB
      max-request-size: 915MB

server:
  error:
    include-message: always

constants:
  filePath: Documents/projects/freevoice/videos

